[package]
name = "oox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
pom = "3.2.0"
pest = "2.0"
pest_derive = "2.0"
ordered-float = "3.4.0"
itertools = "0.10.5"
